services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    volumes:
      - inventory_pg_data:/var/lib/postgresql/data

volumes:
  inventory_pg_data:
